export const formCopy = {
	en: {
		language: 'English',
		productName: 'Product Name',
		productLabel: 'Product Label',
		productCategories: 'Product Categories',
		productDescription: 'Product Description',
		currency: 'eur',
		addBtn: 'add item',
		updateBtn: 'update',
		deleteBtn: 'delete',
		error: 'all fields must be filled !!!',
	},
	sw: {
		language: 'Swahili',
		productName: 'Jina la bidhaa',
		productLabel: 'Lebo ya Bidhaa',
		productCategories: 'Jamii Jamii',
		productDescription: 'Maelezo ya bidhaa',
		currency: 'TSh',
		addBtn: 'ongeza kipengee',
		updateBtn: 'sasisha',
		deleteBtn: 'futa',
		error: 'uwanja wote lazima ujazwe !!!',
	},
}
